load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = ["root.go"],
    importpath = "asset-tracker/services/label_service/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/label/renderer",
        "//pkg/label_manager",
        "//pkg/rendered_label_storage",
        "//proto/label_service",
        "//services/label_service/server",
        "@com_github_aws_aws_sdk_go_v2_config//:config",
        "@com_github_aws_aws_sdk_go_v2_service_dynamodb//:dynamodb",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_viper//:viper",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//reflection",
        "@org_uber_go_zap//:zap",
    ],
)
