load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "asset",
    srcs = [
        "asset.go",
        "id.go",
    ],
    importpath = "asset-tracker/src/core/asset",
    visibility = ["//visibility:public"],
)
