load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "server",
    srcs = ["server.go"],
    importpath = "asset-tracker/services/label_service/server",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/core/asset",
        "//pkg/label",
        "//pkg/label_manager",
        "//proto/label_service",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_uber_go_zap//:zap",
    ],
)
