load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "label_service_proto",
    srcs = ["label_service.proto"],
    visibility = ["//visibility:public"],
    deps = ["//proto/asset_common:asset_common_proto"],
)

go_proto_library(
    name = "label_service_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "asset-tracker/proto/label_service",
    proto = ":label_service_proto",
    visibility = ["//visibility:public"],
    deps = ["//proto/asset_common"],
)

go_library(
    name = "label_service",
    embed = [":label_service_go_proto"],
    importpath = "asset-tracker/proto/label_service",
    visibility = ["//visibility:public"],
)
